### ISSUE TITLE
Миграция в fabric (посмотреть библиотечные моды)

### ISSUE THREAD

**Issue by PiiosS** [Dimas-Studio/DimasRPG-c7c9f6a4#71]

**Comment by PiiosS** [comment]
@Niketats какие есть моды для написания и на forge, и на fabric?

**Comment by Andrey-66** [comment]
@Niketats

**Comment by Niketats** [comment]
https://docs.architectury.dev/api/introduction#:~:text=Architectury%20API%20is%20an%20optional,with%20new%20hooks%20and%20features

**Comment by Niketats** [comment]
https://docs.architectury.dev/start
